#!/usr/bin/python
import dinoliteuvccontrol
import argparse
import time
import pprint


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--debug', action='store_true', help='Enable verbose/debug output')
    args = parser.parse_args()

    return args


def run(worker):
    worker.work()
    worker.display_shutdown_message(0)


def main():
    args = parse_args()
    worker = dinoliteuvccontrol.DinoLiteUVCControl(args)
    try:
        run(worker)
    except (KeyboardInterrupt, EOFError, UnboundLocalError):
        worker.display_shutdown_message(1)


if __name__ == "__main__":
    main()
